name: test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y xdotool xvfb x11-apps imagemagick chromium
      - run: |
          Xvfb :99 -screen 0 1024x768x24 &
          echo 'DISPLAY=:99' >> "$GITHUB_ENV"
      - run: |
          chromium &
          sleep 5
          xdotool type 'Hello, World!'
          xdotool key Return
      - run: |
          xwd -root -display :99 -silent | convert xwd:- png:/tmp/screenshot.png
      - uses: actions/upload-artifact@v4
        with:
          path: /tmp/screenshot.png
